name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js v20.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - run: npx changelogithub --no-group
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Use npm official registry
        run: pnpm config set registry https://registry.npmjs.org/

      - run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
